header added
SaveAna/goit-testing pull request #1
Opened 2022-10-31 17:44 UTC by SaveAna

Маленька практика :)

2022-10-31 20:04 UTC, latikaann approved these changes
Привіт)

2022-10-31 20:04 UTC, latikaann commented on index.html
> +            <h2><span class="accent">Team</span>Logo</h2>
Лого зробити посиланням

2022-10-31 20:07 UTC, latikaann requested changes
Зробити посилання

2022-11-01 15:57 UTC, latikaann approved these changes
Ок

2022-11-01 16:38 UTC, merged

2022-11-03 21:04 UTC, ViktoriiaKN reviewed
Ок

2022-11-03 21:05 UTC, ViktoriiaKN commented
Я перевірила чи ні?

2022-11-03 21:47 UTC, SaveAna commented
так )

2022-11-03 21:56 UTC, latikaann commented
Ні, Віка лише коммент додала, не перевірила.

2022-11-03 22:06 UTC, SaveAna commented
ага, вже бачу. ну то нічого, гілка вже закрита. якби ніхто не перевірив, в мене б кнопка мердж світилась помаранчевим )
ну то, @ViktoriiaKN  завтра спробуєш перевірити гілку Тані )