add test-section
SaveAna/goit-testing pull request #17
Opened 2022-11-06 18:18 UTC by YuriiSVL

2022-11-06 18:21 UTC, YablonskaTanya requested changes
Все чудово але додай margin-top: 100px

2022-11-06 18:43 UTC, YablonskaTanya requested changes
Все добре! Можна мерджити

2022-11-06 23:17 UTC, SaveAna commented
ви видалили і закрили пулл, тому не можу змержити. не бачила, що ви писали

2022-11-06 23:20 UTC, SaveAna commented
обов'язково після другої перевірки нажимайте approve, бо інакше висвічується, що треба зробити зміни і тому merging is blocked

2022-11-06 23:24 UTC, SaveAna approved these changes
ok

2022-11-07 12:20 UTC, YablonskaTanya approved these changes

2022-11-07 12:22 UTC, merged