Додаю модалку
SaveAna/goit-testing pull request #19
Opened 2022-11-07 22:37 UTC by olhacrash

Передивiться та перевiрте

2022-11-07 22:54 UTC, latikaann approved these changes

2022-11-07 23:06 UTC, SaveAna commented
все супер, але намагайтесь писати комміти англійською ) поки не мерджу, нехай ще завтра @TarasVarvarych теж потренується перевіряти , залишати коментарі і відправляти на переробку

2022-11-08 09:45 UTC, YablonskaTanya requested changes
Треба до button додати клас та зробити border 4px. А також змінити у div клас з box на box-modal, тому що клас box вже використовується і пішло накладення розмітки одна на іншу.

2022-11-08 18:34 UTC, SaveAna approved these changes
ok

2022-11-08 18:41 UTC, YablonskaTanya approved these changes
OK!

2022-11-08 22:24 UTC, merged