add section boxes
SaveAna/goit-testing pull request #8
Opened 2022-11-03 21:46 UTC by YablonskaTanya

додала секцію з анімаціями. Давайте правки. Можливо колір. Щось простеньке

2022-11-03 21:54 UTC, latikaann requested changes

2022-11-03 21:54 UTC, latikaann commented on index.html
> +      A transition is triggered when hovering over a container
Зміни колір на синій

2022-11-03 22:07 UTC, YablonskaTanya commented on index.html
> +      A transition is triggered when hovering over a container
ok

2022-11-04 04:32 UTC, ViktorKryvorotov commented on css/styles.css
> +  transition-duration: 3000ms;
Зміни тривалість-переходу на 3005ms))))

2022-11-04 07:58 UTC, YablonskaTanya commented on css/styles.css
> +  transition-duration: 3000ms;
добре)

2022-11-04 08:09 UTC, ViktorKryvorotov approved these changes

2022-11-05 17:42 UTC, SaveAna commented
@latikaann привіт, підтверджуєш зміни? можна зливати ?

2022-11-05 17:45 UTC, YablonskaTanya commented
Я все виправила! Можна зливати!

2022-11-05 20:06 UTC, SaveAna commented
ок

2022-11-05 20:06 UTC, merged